apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: website
  name: website
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: website
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: website
    spec:
      containers:
      - image: website
        name: website
        imagePullPolicy: Never
        resources: {}
        ports:
          - containerPort: 80
          - containerPort: 3000
status: {}