apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    run: website
spec:
  ports:
  - port: 80
    name: get
    protocol: TCP
  - port: 3000
    name: socket
    protocol: TCP
  selector:
    app: website
  type: NodePort